# Name: fhir-ig-publish-cd
# Usage:


parameters:
  - name: builds
    type: object
    default: []

  - name: environments
    type: object

  - name: settings
    type: object


stages:
  - stage: build
    jobs:
      - ${{ each build in parameters.builds }}:
        - template: /.azure/templates/jobs/fhir_ig_publisher.yml
          parameters:
            name: ${{ build.name }}
            repoName: ${{ build.repoName }} 
            ${{ if build.path }}:
              path: ${{ build.path }}
            publisherVersion: ${{ coalesce(build.settings.publisherVersion, parameters.settings.publisherVersion, '1.1.128') }}
            ${{ if parameters.settings.javaVersion }}:
              javaVersion:  ${{ parameters.settings.javaVersion }}
            artifactName:  ${{ build.name }}

  - ${{ each environment in parameters.environments }}:
    - stage: ${{ environment.name }}
      dependsOn:
        - build
        - ${{ if environment.dependsOn }}:
          - ${{ environment.dependsOn }}
      jobs:
        - ${{ each build in parameters.builds }}:
          - deployment: ${{ build.name }}
            environment: ${{ coalesce(environment.environment, format('{0}', environment.name) ) }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - download: current
                      artifact: ${{ build.name }}
                    - ${{ if eq(environment.type, 'webapp') }}:
                      - template: /.azure/templates/steps/static_app_service_deploy.yml
                        parameters:
                          path: $(Pipeline.Workspace)/${{ build.name }}
                          webAppName: ${{ coalesce(environment.webAppName, format('{0}-{1}',coalesce(build.name,build.settings.webAppName,parameters.settings.webAppName), environment.name)) }}
                          webAppRegion: ${{ coalesce(environment.webAppRegion, 'westeurope') }}
                          azureSubscriptionName: ${{ coalesce(environment.azureSubscriptionName, parameters.settings.azureSubscriptionName) }}
                          authenticated: ${{ coalesce(environment.authenticated, true) }}
                    - ${{ if eq(environment.type, 'package') }}:
                      - template: /.azure/templates/steps/publish_npm_package.yml
                        parameters:
                          organization: ${{  parameters.settings.organization }}
                          path: $(Pipeline.Workspace)/${{ build.name }}/package.tgz
                          feed: ${{ environment.feed }}
                          
              
            

