# fhir-ig-publish-jobs.yml
#
# Description: 
#  

parameters:
  - name: name
    type: string

  - name: path
    type: string
    default: ''

  - name: repoName
    type: string

  - name: publisherVersion
    type: string
    default: '1.1.125'

  - name: javaVersion
    type: string
    default: '11'
    values:
      - '9'
      - '11'
      - '17'

  - name: artifactName
    type: string


jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
      
      ####################################################################################
      ####################################################################################
      ####################################################################################
      - checkout: ${{ parameters.repoName }}
        path: igs

      - template: /.azure/templates/steps/fhir_ig_publisher.yml
        parameters:
          path: $(Pipeline.Workspace)/igs/${{ parameters.path }}
          publisherVersion: ${{ parameters.publisherVersion }}
          javaVersion:  ${{ parameters.javaVersion }}
          artifactName:  ${{ parameters.artifactName }}