# fhir-ig-publish-jobs.yml
#
# Description: 
#  

parameters:
  - name: name
    type: string
  - name: path
    type: string
    default: /
  - name: repoName
    type: string
  - name: publisherVersion
    type: string
    default: '1.1.125'
  - name: javaVersion
    type: string
    default: '11'
    values:
      - '9'
      - '11'
      - '17'

  - name: webAppName
    type: string
    
  - name: webAppRegion
    type: string
    default: westeurope
    
  - name: azureSubscriptionName
    type: string


jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - name: sourceFolderPath
        value: $(Pipeline.Workspace)/igs${{ parameters.path }}
    steps: 
      ####################################################################################
      ####################################################################################
      ####################################################################################
      - checkout: ${{ parameters.repoName }}
        path: igs

      - task: NodeTool@0
        inputs:
          versionSpec: '12.x' 
      - script: |
          npm install -g fsh-sushi
        displayName: Install SUSHI

      ####################################################################################
      ####################################################################################
      ####################################################################################
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '${{ parameters.javaVersion }}'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
      - task: UseRubyVersion@0
        inputs:
          versionSpec: '>= 2.5'
          addToPath: true

      - script: |
          gem install rails && rails -v
          gem install bundler
          gem install jekyll bundler
        displayName: 'Installing Jekyll'
      ####################################################################################
      ####################################################################################
      ####################################################################################
      - script: |
          curl -L -o $(pipeline.workspace)/publisher.jar https://github.com/HL7/fhir-ig-publisher/releases/download/${{ parameters.publisherVersion }}/publisher.jar
        displayName: "Download FHIR IG Publisher - ${{ parameters.publisherVersion }}"
      
      - script: |
          java -jar $(pipeline.workspace)/publisher.jar -ig $(sourceFolderPath) -destination $(Build.ArtifactStagingDirectory)
          ls $(Pipeline.Workspace)
          ls $(sourceFolderPath)/output
        displayName: "Run FHIR IG Publisher - ${{ parameters.publisherVersion }}"

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(sourceFolderPath)/output
          artifactName: published
      
      - task: AzureCLI@2
        displayName: Publish To Web Site ${{ parameters.webAppName }}
        inputs:
          azureSubscription: ${{ parameters.azureSubscriptionName }}
          scriptType: bash
          scriptLocation: inlineScript
          workingDirectory: $(sourceFolderPath)/output
          inlineScript: |
            az webapp up --location ${{ parameters.webAppRegion }} --name ${{ parameters.webAppName }} --html
      

