# fhir-ig-publish-jobs.yml
#
# Description: 
#  

parameters:
  - name: name
    type: string

  - name: repos
    type: object

  - name: version
    type: string

    
  - name: label
    type: string

  - name: publisherVersion
    type: string
    default: '1.1.125'

  - name: javaVersion
    type: string
    default: '11'
    values:
      - '9'
      - '11'
      - '17'

  - name: artifactName
    type: string


jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
      
      ####################################################################################
      ####################################################################################
      ####################################################################################
      - ${{ each repo in parameters.repos }}:
        - checkout: ${{ repo }}
          path: igs/${{ repo }}

      - template: /.azure/templates/steps/fhir_ig_publisher.yml
        parameters:
          path: $(Pipeline.Workspace)/igs
          publisherVersion: ${{ parameters.publisherVersion }}
          javaVersion:  ${{ parameters.javaVersion }}
          version:  ${{ parameters.version }}
          label:  ${{ parameters.label }}
          artifactName:  ${{ parameters.artifactName }}