# fhir-ig-publish-jobs.yml
#
# Description: 
#  

parameters:
  
  - name: name
    type: string

  - name: feed
    type: string
  - name: path
    type: string


jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
      - task: Npm@1
        inputs:
          command: custom
          publishRegistry: useFeed
          publishFeed: ${{ parameters.feed }}
          customCommand: publish ${{ parameters.path }}