# fhir-ig-publish-jobs.yml
#
# Description: 
#  

parameters:
  - name: name
    type: string

  - name: path
    type: string

  - name: webAppName
    type: string
    
  - name: webAppRegion
    type: string
    default: westeurope
    
  - name: azureSubscriptionName
    type: string

  - name: authenticated
    type: boolean
    default: true
  - name: preSteps
    type: stepList
    default: []

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
      - ${{ parameters.preSteps }}
      - task: AzureCLI@2
        displayName: Publish To Web Site ${{ parameters.webAppName }}
        inputs:
          azureSubscription: ${{ parameters.azureSubscriptionName }}
          scriptType: pscore
          scriptLocation: inlineScript
          workingDirectory: ${{ parameters.path }}
          inlineScript: |
            $isAuthenticated = "${{ parameters.authenticated }}".ToLower() -eq "true"

            az webapp up `
              --location ${{ parameters.webAppRegion }} `
              --name ${{ parameters.webAppName }} `
              --html

            
            if($isAuthenticated){
              $app = az ad app create `
                        --display-name ${{ parameters.webAppName }} `
                        --web-redirect-uris https://${{ parameters.webAppName }}.azurewebsites.net/.auth/login/aad/callback `
                        --identifier-uris api://${{ parameters.webAppName }} | ConvertFrom-Json
              $creds = az ad app credential reset --id $($app.id) | ConvertFrom-Json
              $password = $creds.password
              az webapp auth update --enabled true `
                  --action LoginWithAzureActiveDirectory `
                  --aad-allowed-token-audiences https://https://${{ parameters.webAppName }}.azurewebsites.net/.auth/login/aad/callback `
                  --aad-client-id $($app.appId) --aad-client-secret $password `
                  --aad-token-issuer-url https://login.microsoftonline.com/common/oauth2/v2.0/token
            }
            else{
                az webapp auth update --enabled false
            }